#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'timezone',
    :path => 'vendor/cookbooks/timezone'

cookbook 'build-essential',
    :path => 'vendor/cookbooks/build-essential'

cookbook 'apt',
    :path => 'vendor/cookbooks/apt'

cookbook 'python',
    :path => 'vendor/cookbooks/python'

cookbook 'nginx',
    :path => 'vendor/cookbooks/nginx'

cookbook 'redis',
    :path => 'vendor/cookbooks/redis'

cookbook 'mongodb',
    :path => 'vendor/cookbooks/mongodb'
